# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pharmacy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pharmacy

  pod 'Swinject'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  
  target 'PharmacyTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
    pod 'Swinject'
  end

end
